spring:
  rabbitmq:
    username: admin
    password: docker@2019!
    port: 5672
    host: 10.200.133.105
  datasource:
    druid:
      maxActive: 500
      initialSize: 5
      minIdle: 5
      maxWait: 60000
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: -1
      validationQuery:  select 1
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000  #（毫秒）
      minEvictableIdleTimeMillis: 25200000   #（毫秒）
      removeAbandoned: true
      removeAbandonedTimeout: 1800    #设置成你服务中service的最长运行时间（单位秒）
      logAbandoned: true
      filters: mergeStat
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=6000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    host: 10.200.133.105
    port: 6379
    password: docker@2019!
    lettuce:
      pool:
        max-active: 8  #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
    timeout: 10000ms #连接超时时间（毫秒）


mybatis:
  mapper-locations: classpath:/mappers/*Mapper.xml

pagehelper:
  reasonable: true
  helper-dialect: mysql

server:
  tomcat:
    max-threads: 200 #默认是200
    max-connections: 10000 #默认是10000
    max-http-post-size: 10485760
    uri-encoding: UTF-8
    accept-count: 2

app:
  swagger:
    enable: true
    description: 接口文档
    version: 1.0
    author: DEV

