server:
  port: 8092

spring:
  datasource:
    url: jdbc:mysql://10.200.133.105:3306/service_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: docker@2019!
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  swagger:
    enable: true
    basePackage: com.xyz.service.demo.controller
    title: service-demo
    description: 接口文档
    version: 1.0
    author: DEV