server:
  port: 8088
logging:
  config: classpath:logback.xml

xxl:
  job:
    executor:
      appname: xxl-job-executor
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1
    admin:
      addresses: http://10.200.133.105:8080/xxl-job-admin
    accessToken:

dingding:
  url: https://oapi.dingtalk.com/robot/send?access_token=f1bcffa05a924cb03154200bd5a7ac9327202f802e65af612f05721af31c846c
