server:
  port: 9093

spring:
  datasource:
    url: jdbc:mysql://10.200.133.105:3306/db_storage?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: docker@2019!
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  swagger:
    basePackage: com.xyz.service.storage.controller
    title: service-storage
