server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
      - id: app-demo
        uri: lb://app-demo
        predicates:
        - Path= /demo/**
        filters:
        - StripPrefix=1
